<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.6</Version>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Pingmint.AzureDevOps</PackageId>
    <Title>Pingmint.AzureDevOps</Title>
    <Authors>Joe Gallagher</Authors>
    <Description>A .NET library for interacting with the Azure DevOps API.</Description>
    <RepositoryUrl>https://github.com/JoeGaggler/dotnet-azure-devops-api</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <None Include="../../LICENSE" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
